spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_LOCAL}:${MYSQL_PORT_LOCAL}/${MYSQL_DB_LOCAL}
    username: ${MYSQL_USER_LOCAL}
    password: ${MYSQL_PASSWORD_LOCAL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGODB_URI_LOCAL}
      database: ${MONGODB_DATABASE}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: Authorization-refresh

ncloud:
  accessKey: ${NCLOUD_ACCESS_KEY}
  secretKey: ${NCLOUD_SECRET_KEY}
  objectStorage:
    bucket: ${OBJECT_STORAGE_BUCKET}
  clovaSpeech:
    secretKey: ${CLOVA_SECRET_KEY}
    invokeUrl: ${CLOVA_INVOKE_URL}

openai:
  key: ${OPENAI_KEY}
  model: ${OPENAI_MODEL}

google:
  refreshToken: ${GOOGLE_REFRESH_TOKEN}
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  firebase:
    projectId: ${FIREBASE_PROJECT}