spring:
  application:
    name: kbsf
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  output:
    ansi:
      enabled: always
logging:
  level:
    com.yl3k: debug
    org.springframework.boot: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace
